---
- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: True
  gather_facts: False
  tags:
    - application_servers
    - flask

  roles:
    - flask

...
