---
- name: Import the DB tier
  import_playbook: provision_database_tier.yml

- name: Import the APP tier
  import_playbook: provision_app_tier.yml

- name: Import the LB tier
  import_playbook: provision_load_balancer_tier.yml

- name: Import end-to-end smoketests
  import_playbook: smoketests.yml

...
